name       : mate-menus
version    : 1.14.0
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-menus-1.14.0.tar.xz : 26585cafa82496e22851fd7c767260797eb029d24698ca8059ddfe3f70226cc5
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : Provides the MATE implementation of XDG Menus
description: |
    The libmate-menu library implements the "Desktop Menu Specification" from freedesktop.org
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
