name       : mate-menus
version    : 1.20.0
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-menus-1.20.0.tar.xz : 0fdadb1ba0950c14a72802c8a5afae99c46ca20ef3c7b9f1854bd5a5da3433f0
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : Provides the MATE implementation of XDG Menus
description: |
    The libmate-menu library implements the "Desktop Menu Specification" from freedesktop.org
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
