name       : mate-menus
version    : 1.22.0
release    : 13
source     :
    - https://github.com/mate-desktop//mate-menus/archive/v1.22.0.tar.gz : b6ae5d6af8d596a3854b33826df8cae2e31f2dce2dd5b4817eadf36e9eaaea9b
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : Provides the MATE implementation of XDG Menus
description: |
    The libmate-menu library implements the "Desktop Menu Specification" from freedesktop.org
builddeps  :
    - mate-common
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
