name       : mate-menus
version    : 1.18.0
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-menus-1.18.0.tar.xz : f07cdb952934b732678ed37a9cd740c8860e9e2d0ddb4d73a8d06cdccfc87e16
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : Provides the MATE implementation of XDG Menus
description: |
    The libmate-menu library implements the "Desktop Menu Specification" from freedesktop.org
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
