name       : mate-menus
version    : 1.22.1
release    : 14
source     :
    - https://github.com/mate-desktop/mate-menus/releases/download/v1.22.1/mate-menus-1.22.1.tar.xz : 800d26bdba7762660ec8513cf5bcc58ff173fa1ae96621b21d17e6e0ccf1064e
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : Provides the MATE implementation of XDG Menus
description: |
    The libmate-menu library implements the "Desktop Menu Specification" from freedesktop.org
builddeps  :
    - mate-common
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
