name       : mate-menus
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-menus-1.16.0.tar.xz : 85d51e02cd94f33b13265ba4847e93d99cef5ec3ce7ee4499958f3afe3013c33
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : Provides the MATE implementation of XDG Menus
description: |
    The libmate-menu library implements the "Desktop Menu Specification" from freedesktop.org
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
